 import  NavBar  from '@/components/Navbar';
import Head from 'next/head';
import React from 'react';
import Box from '@mui/material/Box'
import Footer from '../Footer';



type layoutProps = {
  children: React.ReactNode;
  justifyContent?: string;
};

const WithMain: React.FC<layoutProps> = ({ children}) => {
  return (
    <>
      <Head>
        <title>Aiico | Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box minHeight={'100vh'} >
        < NavBar  />
        {children}
        <Footer />
      </Box>
    </>
  );
};

export default  WithMain;
